<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy_events.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string event_name = 1;</code>
     */
    protected $event_name = '';
    /**
     * Generated from protobuf field <code>int64 time = 2;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>int64 server_time = 3;</code>
     */
    protected $server_time = 0;
    /**
     * Generated from protobuf field <code>.Event.User user = 4;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>.Event.Common common = 5;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>.Event.Payload payload = 6;</code>
     */
    protected $payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $event_name
     *     @type int|string $time
     *     @type int|string $server_time
     *     @type \App\Protos\Event\User $user
     *     @type \App\Protos\Event\Common $common
     *     @type \App\Protos\Event\Payload $payload
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\Metadata\DummyEvents::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string event_name = 1;</code>
     * @return string
     */
    public function getEventName()
    {
        return $this->event_name;
    }

    /**
     * Generated from protobuf field <code>string event_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventName($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 time = 2;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int64 time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 server_time = 3;</code>
     * @return int|string
     */
    public function getServerTime()
    {
        return $this->server_time;
    }

    /**
     * Generated from protobuf field <code>int64 server_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServerTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->server_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Event.User user = 4;</code>
     * @return \App\Protos\Event\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.Event.User user = 4;</code>
     * @param \App\Protos\Event\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\Event\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Event.Common common = 5;</code>
     * @return \App\Protos\Event\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.Event.Common common = 5;</code>
     * @param \App\Protos\Event\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\Event\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Event.Payload payload = 6;</code>
     * @return \App\Protos\Event\Payload|null
     */
    public function getPayload()
    {
        return $this->payload;
    }

    public function hasPayload()
    {
        return isset($this->payload);
    }

    public function clearPayload()
    {
        unset($this->payload);
    }

    /**
     * Generated from protobuf field <code>.Event.Payload payload = 6;</code>
     * @param \App\Protos\Event\Payload $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\Event\Payload::class);
        $this->payload = $var;

        return $this;
    }

}

