<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy_events.proto

namespace App\Protos\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Event.Common</code>
 */
class Common extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string app_version = 1;</code>
     */
    protected $app_version = '';
    /**
     * Generated from protobuf field <code>string device_model = 2;</code>
     */
    protected $device_model = '';
    /**
     * Generated from protobuf field <code>string language = 3;</code>
     */
    protected $language = '';
    /**
     * Generated from protobuf field <code>string resolution = 4;</code>
     */
    protected $resolution = '';
    /**
     * Generated from protobuf field <code>string platform = 5;</code>
     */
    protected $platform = '';
    /**
     * Generated from protobuf field <code>string loc_country_id = 6;</code>
     */
    protected $loc_country_id = '';
    /**
     * Generated from protobuf field <code>string loc_province_id = 7;</code>
     */
    protected $loc_province_id = '';
    /**
     * Generated from protobuf field <code>string loc_city_id = 8;</code>
     */
    protected $loc_city_id = '';
    /**
     * Generated from protobuf field <code>string client_ip = 9;</code>
     */
    protected $client_ip = '';
    /**
     * Generated from protobuf field <code>string os_version = 10;</code>
     */
    protected $os_version = '';
    /**
     * Generated from protobuf field <code>string network_carrier = 11;</code>
     */
    protected $network_carrier = '';
    /**
     * Generated from protobuf field <code>string device_brand = 12;</code>
     */
    protected $device_brand = '';
    /**
     * Generated from protobuf field <code>string os_name = 13;</code>
     */
    protected $os_name = '';
    /**
     * Generated from protobuf field <code>string network_type = 14;</code>
     */
    protected $network_type = '';
    /**
     * Generated from protobuf field <code>repeated string ab_version = 15;</code>
     */
    private $ab_version;
    /**
     * Generated from protobuf field <code>string referer = 16;</code>
     */
    protected $referer = '';
    /**
     * Generated from protobuf field <code>string module_name = 17;</code>
     */
    protected $module_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app_version
     *     @type string $device_model
     *     @type string $language
     *     @type string $resolution
     *     @type string $platform
     *     @type string $loc_country_id
     *     @type string $loc_province_id
     *     @type string $loc_city_id
     *     @type string $client_ip
     *     @type string $os_version
     *     @type string $network_carrier
     *     @type string $device_brand
     *     @type string $os_name
     *     @type string $network_type
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ab_version
     *     @type string $referer
     *     @type string $module_name
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\Metadata\DummyEvents::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string app_version = 1;</code>
     * @return string
     */
    public function getAppVersion()
    {
        return $this->app_version;
    }

    /**
     * Generated from protobuf field <code>string app_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_model = 2;</code>
     * @return string
     */
    public function getDeviceModel()
    {
        return $this->device_model;
    }

    /**
     * Generated from protobuf field <code>string device_model = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 3;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resolution = 4;</code>
     * @return string
     */
    public function getResolution()
    {
        return $this->resolution;
    }

    /**
     * Generated from protobuf field <code>string resolution = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setResolution($var)
    {
        GPBUtil::checkString($var, True);
        $this->resolution = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform = 5;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>string platform = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loc_country_id = 6;</code>
     * @return string
     */
    public function getLocCountryId()
    {
        return $this->loc_country_id;
    }

    /**
     * Generated from protobuf field <code>string loc_country_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLocCountryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->loc_country_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loc_province_id = 7;</code>
     * @return string
     */
    public function getLocProvinceId()
    {
        return $this->loc_province_id;
    }

    /**
     * Generated from protobuf field <code>string loc_province_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLocProvinceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->loc_province_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loc_city_id = 8;</code>
     * @return string
     */
    public function getLocCityId()
    {
        return $this->loc_city_id;
    }

    /**
     * Generated from protobuf field <code>string loc_city_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLocCityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->loc_city_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_ip = 9;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->client_ip;
    }

    /**
     * Generated from protobuf field <code>string client_ip = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string os_version = 10;</code>
     * @return string
     */
    public function getOsVersion()
    {
        return $this->os_version;
    }

    /**
     * Generated from protobuf field <code>string os_version = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setOsVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->os_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network_carrier = 11;</code>
     * @return string
     */
    public function getNetworkCarrier()
    {
        return $this->network_carrier;
    }

    /**
     * Generated from protobuf field <code>string network_carrier = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setNetworkCarrier($var)
    {
        GPBUtil::checkString($var, True);
        $this->network_carrier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_brand = 12;</code>
     * @return string
     */
    public function getDeviceBrand()
    {
        return $this->device_brand;
    }

    /**
     * Generated from protobuf field <code>string device_brand = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceBrand($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_brand = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string os_name = 13;</code>
     * @return string
     */
    public function getOsName()
    {
        return $this->os_name;
    }

    /**
     * Generated from protobuf field <code>string os_name = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setOsName($var)
    {
        GPBUtil::checkString($var, True);
        $this->os_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network_type = 14;</code>
     * @return string
     */
    public function getNetworkType()
    {
        return $this->network_type;
    }

    /**
     * Generated from protobuf field <code>string network_type = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setNetworkType($var)
    {
        GPBUtil::checkString($var, True);
        $this->network_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ab_version = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAbVersion()
    {
        return $this->ab_version;
    }

    /**
     * Generated from protobuf field <code>repeated string ab_version = 15;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAbVersion($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ab_version = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string referer = 16;</code>
     * @return string
     */
    public function getReferer()
    {
        return $this->referer;
    }

    /**
     * Generated from protobuf field <code>string referer = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setReferer($var)
    {
        GPBUtil::checkString($var, True);
        $this->referer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string module_name = 17;</code>
     * @return string
     */
    public function getModuleName()
    {
        return $this->module_name;
    }

    /**
     * Generated from protobuf field <code>string module_name = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setModuleName($var)
    {
        GPBUtil::checkString($var, True);
        $this->module_name = $var;

        return $this;
    }

}

