<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy_events.proto

namespace App\Protos\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Event.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Event.Payload.Goods goods = 1;</code>
     */
    private $goods;
    /**
     * Generated from protobuf field <code>string order_id = 2;</code>
     */
    protected $order_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Protos\Event\Payload\Goods>|\Google\Protobuf\Internal\RepeatedField $goods
     *     @type string $order_id
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\Metadata\DummyEvents::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Event.Payload.Goods goods = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGoods()
    {
        return $this->goods;
    }

    /**
     * Generated from protobuf field <code>repeated .Event.Payload.Goods goods = 1;</code>
     * @param array<\App\Protos\Event\Payload\Goods>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGoods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protos\Event\Payload\Goods::class);
        $this->goods = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

}

