<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy_events.proto

namespace App\Protos\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Event.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>string web_id = 2;</code>
     */
    protected $web_id = '';
    /**
     * Generated from protobuf field <code>string ssid = 3;</code>
     */
    protected $ssid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $web_id
     *     @type string $ssid
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\Metadata\DummyEvents::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string web_id = 2;</code>
     * @return string
     */
    public function getWebId()
    {
        return $this->web_id;
    }

    /**
     * Generated from protobuf field <code>string web_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWebId($var)
    {
        GPBUtil::checkString($var, True);
        $this->web_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ssid = 3;</code>
     * @return string
     */
    public function getSsid()
    {
        return $this->ssid;
    }

    /**
     * Generated from protobuf field <code>string ssid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSsid($var)
    {
        GPBUtil::checkString($var, True);
        $this->ssid = $var;

        return $this;
    }

}

